agent:
  code:
    max_tokens: null
    model: gpt-4o-2024-11-20
    temp: 1.0
  data_preview: false
  expose_prediction: false
  feedback:
    max_tokens: 8192
    model: gpt-4o-2024-11-20
    temp: 0.5
  k_fold_validation: 1
  multi_seed_eval:
    num_seeds: 3
  num_workers: 4
  search:
    debug_prob: 0.5
    max_debug_depth: 3
    num_drafts: 3
  stages:
    stage1_max_iters: 10
    stage2_max_iters: 6
    stage3_max_iters: 6
    stage4_max_iters: 9
  steps: 5
  type: parallel
  vlm_feedback:
    max_tokens: null
    model: gpt-4o-2024-11-20
    temp: 0.5
copy_data: true
data_dir: data
debug:
  stage4: false
eval: null
exec:
  agent_file_name: runfile.py
  format_tb_ipython: false
  timeout: 3600
exp_name: run
experiment:
  num_syn_datasets: 1
generate_report: true
goal: null
log_dir: logs
preprocess_data: false
report:
  model: gpt-4o-2024-11-20
  temp: 1.0
workspace_dir: workspaces
